DROP TABLE passports CASCADE;
DROP TABLE companies CASCADE;
DROP TABLE licenses CASCADE;
DROP TABLE customers CASCADE;
DROP TABLE cars CASCADE;
DROP TABLE metal_deals CASCADE;
DROP TABLE metal_items CASCADE;
DROP TABLE metal_marks CASCADE;
DROP TABLE metal_costs CASCADE;
DROP VIEW  customer_passports 
